# Generated by Django 2.2.24 on 2021-08-03 03:20

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', student.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to='student.StudentClass'),
        ),
    ]
